[workspace]
members = ["cosmic-ext-applet-connect", "kdeconnect-core"]
default-members = ["cosmic-ext-applet-connect", "kdeconnect-core"]
resolver = "3"


[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1.48", features = ["full"] }
tracing = "0.1"
zbus = { version = "5.12", features = ["tokio"] }
