[package]
name = "kdeconnect-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
kdeconnect-core = { path = "../kdeconnect-core" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
